- job_name: 'ec2'
  metrics_path: /metrics
  static_configs:
    - targets: 
      - 3.14.132.192:9100
      - 3.14.132.192:80
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://3.14.132.192
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115